twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig','bootstrap_4_horizontal_layout.html.twig']

    globals: 
         type_fichier : ['memoires','annexes','resumes','presentation','fichessecur','diaporamas','autorisations']
         type_fichier_lit : ['mémoire','annexe','résume','présentation(diaporama du concours national)pour le jury et publiée le lendemain du concours','fiche securité','diaporama', 'autorisations']
        