<?php

namespace App\Repository;
use App\Entity\Elevesinter;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
/**
 * ElevesinterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. cope coller
 */
class ElevesinterRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry, SessionInterface $session)
                    {
                        parent::__construct($registry, Elevesinter::class);
                        $this->session = $session;
                    }
                    
    public function getEleveAutorisation($id)  :   ?Elevesinter
    {
        return $this->createQueryBuilder('e')
            ->andWhere('e.autorisationphotos = :autorisation')
            ->setParameter('autorisation', $id)
            ->getQuery()
            ->getOneOrNullResult();
        
        
        
    }           
                    

}
