parameters:
    locale: 'fr'
    
    
    app.path.photos : '%kernel.project_dir%/public/upload/photos'
    app.path.tempdirectory :  '%kernel.project_dir%/public/temp'
    app.path.thumbtmp :  '%kernel.project_dir%/public/upload/images/tmp'
    type_fichier : ['memoires','annexes','resumes','presentations','fichessecur']
    type_fichier_lit : ['mémoire','annexe','résume','présentation','fiche securité']
    
    app.path.fichiers : '%kernel.project_dir%/public/fichiers'
    
    repertoire_photosinter :  '%kernel.project_dir%/public/upload/images/27/int'
    repertoire_photos_inter : /../public/upload/images/27/int
    app.path.photosinter : '%kernel.project_dir%/public/upload/images/27/int'      #sur le site /../public/upload/images/27/int 
    app.path.photosinterthumb:  '%kernel.project_dir%/public/upload/images/27/int/thumb'     #sur le site /../public/upload/images/27/int/thumb 
    app.path.photosnatthumb: '%kernel.project_dir%/public/upload/images/27/nat/thumb'      #sur le site /../public/upload/images/27/nat/thumb
    app.path.photosnat :  '%kernel.project_dir%/public/upload/images/27/nat'      #sur le site /../public/upload/images/27/nat
    
    app.path.fichiers.localhost : /fichiers
    
    
    
    
    
    
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
