easy_admin :
     entities :
            Centrescia :
                         class : App\Entity\Centrescia 
                         label : 'Centres interacadémiques'
                         list : 
                             fields : 
                                - { property : 'edition.ed', label : 'Edition'}
                                - { property : 'centre'}
                             
                         edit :
                             fields : 
                                - { property : 'edition', type: 'entity' , type_options : { class : 'App\Entity\Edition', query_builder : 'App\Repository\EditionRepository::getEdition', 'choice_label' : 'getEd'}}
                                - { property : 'centre'}
                                
                         new :
                             fields : 
                                - { property : 'edition', type: 'entity' , type_options : { class : 'App\Entity\Edition', query_builder : 'App\Repository\EditionRepository::getEdition', 'choice_label' : 'getEd'}}
                                - { property : 'centre'}
