easy_admin :
    design:
                brand_color: '#FF0000'
                assets:
                    css:
                        # ...
                        - 'css/admin.css'
                menu:
                    - { entity: 'Adminsite' , permission: 'ROLE_SUPER_ADMIN', icon : 'cogs'}
                    - { entity: 'User', label : 'Utilisateurs', permission: 'ROLE_SUPER_ADMIN', icon : 'user' }
                    - label : 'Concours interacadémique'
                      icon : 
                      css_class: 'text-bold'
                      children :
                         - { entity : 'Centrescia', 'label' : 'Centres interacadémiques', icon : 'city'}
                         - { entity : 'Equipesadmin', 'label' : 'Equipes des cia', icon : 'user-friends'}
                    - label : 'Concours national'
                      icon : ''
                      children :
                        - label: 'Equipes'
                        - { label : 'Administration des équipes' , entity : 'Selectionnees', icon : 'user-friends'}
                        
                    - { label: 'Retour à la page d''accueil', route: 'core_home' , icon : 'home'}
                    - { label : 'Deconnexion' , route: 'logout', icon : 'door-open'}

                form_theme:
                - '@EasyAdmin/form/bootstrap_4.html.twig'

