easy_admin :
    entities :
       Adminsite :
            class: App\Entity\Edition
    
            list:
                title : 'Réglage du site'
                max_results: 30
                fields: ['ed', 'annee', 'ville', 'date' ,'lieu' , 'dateouverturesite', 'dateclotureinscription', 'datelimcia', 'datelimnat', 'concourscia','concourscn']
        
            edit : 
                fields :  ['ed', 'annee', 'ville', 'date' , 'lieu', 'dateouverturesite',  'dateclotureinscription', 'datelimcia', 'datelimnat', 'concourscia','concourscn']
                
            new : 
                fields :  ['ed', 'annee', 'ville', 'date' , 'lieu', 'dateouverturesite',  'dateclotureinscription', 'datelimcia', 'datelimnat', 'concourscia','concourscn']