easy_admin :
     entities :
         Livredorjury:
             
             
             class : App\Entity\Livredor
             controller: App\Controller\Admin\LivredoradminController
             templates :
               list: 'Admin/customizations/livredor.html.twig'
             actions :
               - {name : '-new'}
               - {name : 'delete', label : 'effacer'}
            
             list :
                  max_results: 50
                  actions: [ 'delete', '-edit',{name : '-new'}]

                  filters :
                    - 'edition'
                      
                  dql_filter : 'entity.categorie = jury'
                  title : <h2>Le livre d'or du jury</h2>
                  fields: 
                    - {property : 'user.prenomNom', label: 'Prénom Nom'}
                    - {property : 'texte', type  : 'text' }

                  sort: ['user.nom','ASC']

                      
          
            
                       
    
