easy_admin :
    entities :
        Professeurs :
            class :  App\Entity\Professeurs
            label : 'Professeurs'
            controller: App\Controller\Admin\ProfesseursController
            templates:
                       list: 'Admin/customizations/list_profs.html.twig'
          
            list :
                permission: 'ROLE_COMITE'
                filters : [{ property: 'equipesstring' }]
                    
                    
                dql_filter : 
               

                actions : ['-new','-edit','-delete']
                fields :
                    - {property : 'user.nom', label : 'Nom'}
                    - {property : 'user.prenom', label : 'Prénom'}
                    - {property : 'user.adresse', label : 'adresse'}
                    - {property : 'user.code', label : 'CP'}
                    - {property : 'user.ville',label :  'Ville'}
                    - {property : 'user.email',label: 'courriel' }
                    - {property : 'user.phone',label: 'Téléphone' }
                    - {property : 'rne', label : 'code UAI'}
                    - {property : 'nomlycee', label : 'lycée'}
                    - {property : 'communelycee', label : 'ville du lycée'}
                    - {property : 'equipesString', type: 'array', label : 'Equipes'}

                sort : ['user.nom', ASC]
                #form:  # <-- 'form' is applied to both 'new' and 'edit' views

            
