easy_admin :
    entities :
        Professeurs :
            class :  App\Entity\User
            label : 'Professeurs'
            controller: App\Controller\Admin\ProfesseursController
            templates:
                       #list: 'Admin/customizations/list_prof.html.twig'
          
            list :
                permission: 'ROLE_COMITE'
                filters :
                    - 'rne'
                    
                    
                dql_filter : 
               

                actions :
                fields :
                    - {property : 'nom', label : 'Nom'}
                    - {property : 'prenom', label : 'Prénom'}
                    - {property : 'adresse', label : 'adresse'}
                    - {property : 'code', label : 'CP'}
                    - {property : 'ville',label :  'Ville'}
                    - {property : 'email',label: 'courriel' }
                    - {property : 'phone',label: 'Téléphone' }
                    - {property : 'rneId.rne', label : 'code UAI'}
                    - {property : 'rneId.nom', label : 'lycée'}
                    - {property : 'rneId.commune', label : 'ville du lycée'}

                sort : ['nom', ASC]
                #form:  # <-- 'form' is applied to both 'new' and 'edit' views

            
