easy_admin :
    entities :
        Professeurs :
            class :  App\Entity\Equipesadmin
            label : 'Professeurs 1'
            controller: App\Controller\Admin\ProfesseurController
            templates:
                       #list: 'Admin/customizations/list_prof.html.twig'
          
            list :
                permission: 'ROLE_COMITE'
                filters :
                    - 'edition'
                    
                    
                dql_filter : 
               

                actions :
                fields :
                    - {property : 'nomProf1', label : 'Nom'}
                    - {property : 'prenomProf1', label : 'Prénom'}
                    - {property : 'idProf1.rne', label : 'code UAI'}
                    - {property : 'idProf1.adresse', label : 'adresse'}
                    - {property : 'idProf1.code', label : 'CP'}
                    - {property : 'idProf1.ville',label :  'Ville'}
                    - {property : 'idProf1.email',label :  'courriel'}
                    - {property : 'idProf1.phone',label :  'Téléphone'}
                sort : ['nomProf1', ASC]
                #form:  # <-- 'form' is applied to both 'new' and 'edit' views

            
