easy_admin :
    entities :
        Visites :
            class : App\Entity\Visites
            label: Les Visites
            list:
                batch_action: ['delete']
                fields:
                     - 'intitule'
                     - { property: 'equipe.classementEquipe', label : 'Equipe'}
            edit:
                title: 'Modifier une visite'
                actions : ['-delete']
                fields:
                    - 'intitule'
                    - { property: 'equipe', type: 'entity' , type_options : { class : 'App\Entity\Equipes', query_builder : 'App\Repository\EquipesRepository::getEquipes', 'choice_label' : 'getClassementEquipe'}}
                  
                  
                    
       
